apiVersion: v1
kind: Secret
metadata:
  name: node-secret
type: Opaque
data:
  JWT_SECRET: OGMwZDZjZGU2MGFhMzUzZDllZTBhYjJjMzlkYTNlMmM1MzQwZDE5MWVkZDEyZGUzM2I0ZDBkZmQ5NGZlYjc2MzdjNGUxNTg5YzFiODQyMjI4ZmVlOGUxNWQ0M2VjOTcyYjNlYjdiOWJiMzQxNDVlYTY3ZGJkNjgxN2EwCjcyNzg1Cg==
