# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: node-backend
# spec:
#   selector:
#     matchLabels:
#       app: node
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: node
#       containers:
#       - name: node-backend
#         image: cicdmicrosvc1-d4g7c6aehxc5amfa.azurecr.io/omm-node:tag
#         ports:
#         - containerPort: 4000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-backend
        image: cicdmicrosvc1-d4g7c6aehxc5amfa.azurecr.io/omm-node:tag
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: node-secret
        - configMapRef:
            name: node-config

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 20
---

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
